name: Auto Build & Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install pyinstaller requests

      - name: Build EXE
        run: pyinstaller --onefile --windowed calculator.py

      - name: Get Version
        id: get_version
        run: |
          $VERSION = Get-Date -Format "yyyyMMddHHmm"
          echo "VERSION=$VERSION" >> $env:GITHUB_ENV
          echo "Generated version: ${{ env.VERSION }}"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/calculator.exe
          tag_name: v${{ env.VERSION }}
          body: "New update released! Version ${{ env.VERSION }}"
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN  }}

      - name: Update version file
        run: |
          echo "Generated version: ${{ env.VERSION }}"
          echo "${{ env.VERSION }}" > latest_version.txt
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"
          git add latest_version.txt
          git commit -m "Update version to ${{ env.VERSION }}"
          git push
